config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :items
  resources :roles
  resources :permissions
  root "home#index"
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :admins
  has_and_belongs_to_many :permissions

  validates :name, presence: true, uniqueness: true

  def set_permissions(permissions)
    permissions.each do |id|
      permission = Permission.find(id)
      self.permissions << permission
      case permission.subject_class
      when "Part"
        case permission.action
        when "create"
          self.permissions << Permission.where(subject_class: "Item", action: "create")
        when "update"
          self.permissions << Permission.where(subject_class: "Item", action: ["update", "destroy"])
        end
      end
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  skip_before_action :verify_authenticity_token
  #before_action :authenticate_admin!
  #before_action :is_super_admin?

  def index
    @roles = Role.all{|role| role.name != "super_admin"}
    respond_to do |format|
      format.json {  }
    end
  end

  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end
  def create
    @role = Role.new(params.permit(:name))

    respond_to do |format|
      if @role.save
        #format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
       # format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @role = Role.find(params[:id])
    @permissions = @role.permissions
  end

  def edit
    @role = Role.find(params[:id])
    @permissions = Permission.all{|i| ["Item"].include? i.subject_class}.compact
    @role_permissions = @role.permissions.collect{|p| p.id}
  end

  def update
    @role = Role.find(params[:id])
    @role.permissions = []
    @role.set_permissions(params[:permissions]) if params[:permissions]
    @role.name = params[:name]
    
    if @role.save
      respond_to do |format|
        format.json { render json: @role, :status => :ok}
      end
    end
    #@permissions = Permission.all{|i| ["Item"].include? i.subject_class}.compact
    #render 'edit'
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
  
  private

  def is_super_admin?
    redirect_to root_path unless current_admin.super_admin?
  end


end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="">
      <h3>Role <%= @role.name %></h3>
      <%= form_for( @role, :url => role_path, :method => :put) do |f| %>
        <fieldset>
          <h3>Permissions</h3>
        </fieldset>
        <fieldset>
          <table class="table">
            <thead>
              <th >Ability</th>
              <th>Class</th>
              <th>Action</th>
            </thead>
            <tbody>
              <% @permissions.each do |permission| %>
                <tr>
                  <td>
                    <%= permission.name %>
                  </td>
                  <td>
                    <%= permission.subject_class %>
                  </td>
                  <td>
                    <%= permission.action %>
                  </td>
                  <td>
                    <%= check_box_tag 'permissions[]', permission.id, @role_permissions.include?(permission.id), {array: true, class: "check_box"}  %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </fieldset>
        <fieldset>
            <div class="span16 offset2">
              <div class="clearfix">
                <%= f.submit "Update", :class => 'btn primary' %>
                <%= link_to 'Cancel', roles_path %>
              </div>
            </div>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/roles/index.html.erb
<div class="container">
  <div class="row">
    <h3> Listing Roles</h3>
    <div class="col-md-12">
      <%= link_to 'add role', new_role_path%>
      <table class="table">
        <thead>
          <th>Name</th>
          <th></th>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          <% @roles.each do |role| %>
          <tr>
            <td>
              <%= role.name %>
            </td>
            <td>
              <%= link_to 'show', role %>
            </td>
            <td>
              <%= link_to 'edit', edit_role_path(role) %>
            </td>
            <td>
             <%= link_to 'delete role', role, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= link_to 'back', root_path%>

app/views/roles/index.json.erb
{    
  "items":[
    <% @roles.each_with_index do |role,index| %>
      {
        "id"  : "<%= role.id %>",
        "name": "<%= role.name %>",
        "permissions": [
          <% role.permissions.each_with_index do |permission, index|%>
            {
              "id": "<%= permission.id %>",
              "object": "<%= permission.subject_class %>",
              "action": "<%= permission.action %>"
            }
          <% unless index == role.permissions.count - 1 %>
            ,
          <% end %>
          <% end %>

        ]
      }
    <% unless index == @roles.count - 1 %>
      ,
    <% end %>
    <% end %>
  ]
}

app/views/roles/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="authform">
      <h3>Role <%= @role.name %></h3>
      <%= form_for @role do |f| %>
        <% if @role.errors.any? %>
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h2>
              <%= "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:" %>
            </h2>
            <ul>
              <% @role.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
              <% end %>
            </ul>
          </div>

        <% end %>
        <fieldset>
         <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
          

        </fieldset>
          <div class="clearfix"></div>
          <div class="form-group pull-right">
            <%= f.submit "Save", :class => 'btn primary' %>
            <%= link_to 'Cancel', roles_path, :class => 'btn primary' %>
          </div>
          
      <% end %>
    </div>
  </div>
</div>

app/views/roles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12"><p id="notice"><%= notice %></p></div>
  </div>  
  <div class="row">
    <h3>Name: <%= @role.name %></h3>
    <div class="col-md-12">
      <table class="table">
        <thead>
          <th>Name</th>
          <th>Action</th>
          <th>Class</th>
        </thead>
        <tbody>
          <% @permissions.each do |permission| %>
            <tr>
              <td>
                <%= permission.name %>
              </td>
              <td>
                <%= permission.action %>
              </td>
              <td>
                <%= permission.subject_class %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Back', roles_path, :class => 'btn btn-default' %>
    </div>
  </div>
</div>